pipelines:
  default:
    - step:
        name: Build and test
        script:
          - npm install
          - npm test  
    - step:
        name: Deploy
        script:
            - pipe: atlassian/google-cloud-storage-deploy:0.3.5
              variables:
                KEY_FILE: $KEY_FILE
                PROJECT: 'Vidhitsa'
                BUCKET: 'neospec.in'
                SOURCE: '.'